### PR TITLE
11.0

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**

### CODE REVIEW

**Comment by neobuddy89** [comment]
Setting props will conflict with PixelProp utils.

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> Setting props will conflict with PixelProp utils.

What do you think about this https://github.com/Hikari-no-Tenshi/android_frameworks_base/commit/06bd420f213088ffa4e538da53ab6998f2940755 in case system prop will not match?
We can update it along with fingerprint.

**Comment by neobuddy89** [comment]
I tried this earlier, it didn't work. Only solution is to update pixelprop
every month.

In above message, I was saying, your overrides will fail as PixelProp would
override them.

**Comment by Hikari-no-Tenshi** [comment]
I thought it just overrides props only for certain processes without touching original values.
Then i can go another way and disable PixelProps if ro.crdroid.version.security_patch is set.

**Comment by neobuddy89** [comment]
You can check and disable directly in Zygote.java
However, the recommendation would be sticking with PixelProp instead overriding with old dated props. It would provide google goodies and rightfully reflect security patch date.

**Pull request merged**
